changelog:
  exclude:
    labels:
      - ignore in release notes

  categories:
    - title: New Features 🎉
      labels:
        - feature

    - title: Enhancements 🔧
      labels:
        - enhancement
      exclude:
        labels:
          - breaking change

    - title: Fixes 🐞
      labels:
        - bug
      exclude:
        labels:
          - breaking change

    - title: Breaking Changes 🛫
      labels:
        - breaking change

    - title: Docs 📚
      labels:
        - documentation

    - title: Examples & Contrib 💡
      labels:
        - example
        - contrib

    - title: Dependencies 📦
      labels:
        - dependencies

    - title: Other Changes 🦾
      labels:
        - "*"
